apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smart-vineyard-24hlp-tls
  namespace: smart-vineyard
spec:
  secretName: smart-vineyard-24hlp-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - smartvineyard.24hlp.ru
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-vineyard
  namespace: smart-vineyard
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
spec:
  ingressClassName: gitlab-nginx
  rules:
    - host: smartvineyard.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smart-vineyard
                port:
                  name: http
    - host: smartvineyard.24hlp.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smart-vineyard
                port:
                  name: http
  tls:
    - hosts:
        - smartvineyard.ru
      secretName: smart-vineyard-tls
    - hosts:
        - smartvineyard.24hlp.ru
      secretName: smart-vineyard-24hlp-tls
