default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gorgomania      # ← поменяй с postgres на gorgomania
  password: 4555008         # ← твой пароль
  host: localhost

development:
  <<: *default
  database: smart_vineyard_development

test:
  <<: *default
  database: smart_vineyard_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "smart_vineyard_production") %>
  username: <%= ENV.fetch("DB_USER", "rails") %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>