default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gorgomania      # ← поменяй с postgres на gorgomania
  password: 4555008         # ← твой пароль
  host: localhost

development:
  <<: *default
  database: smart_vineyard_development

test:
  <<: *default
  database: smart_vineyard_test

production:
  <<: *default
  database: smart_vineyard_production